export const questions = [
  {
    id: 1,
    topic: "Educación Financiera",
    question: "¿Qué es un presupuesto?",
    options: {
      A: "Una lista de deseos.",
      B: "Un tipo de inversión.",
      C: "Una cuenta bancaria.",
      D: "Un plan de gastos y ahorros.",
    },
    answer: "D",
  },
  {
    id: 2,
    topic: "Educación Financiera",
    question: "¿Por qué es importante ahorrar dinero?",
    options: {
      A: "Solo para comprar artículos de lujo.",
      B: "Para tener seguridad financiera y alcanzar metas futuras.",
      C: "Para pagar todas las deudas de una vez.",
      D: "No es importante si tienes muchos ingresos.",
    },
    answer: "B",
  },
  {
    id: 3,
    topic: "Educación Financiera",
    question: "¿Qué es el interés?",
    options: {
      A: "Un tipo de impuesto.",
      B: "Un descuento en una compra.",
      C: "El precio de un producto.",
      D: "El costo de pedir dinero prestado o la ganancia por prestarlo.",
    },
    answer: "D",
  },
  {
    id: 4,
    topic: "Educación Financiera",
    question: "¿Qué es el crédito?",
    options: {
      A: "Dinero en efectivo.",
      B: "Un regalo de dinero.",
      C: "Una cuenta de ahorros.",
      D: "La capacidad de pedir dinero prestado con la promesa de pagarlo después.",
    },
    answer: "D",
  },
  {
    id: 5,
    topic: "Educación Financiera",
    question: "¿Cuál es la diferencia entre un activo y un pasivo?",
    options: {
      A: "Un activo es una cuenta de ahorros y un pasivo es una inversión.",
      B: "No hay diferencia, son lo mismo.",
      C: "Un activo es algo viejo y un pasivo es algo nuevo.",
      D: "Un activo te genera dinero y un pasivo te quita dinero.",
    },
    answer: "D",
  },
  {
    id: 6,
    topic: "Educación Financiera",
    question: "¿Qué es la diversificación de inversiones?",
    options: {
      A: "Poner todo el dinero en una sola inversión.",
      B: "Solo invertir en acciones.",
      C: "Invertir en un solo país.",
      D: "Distribuir las inversiones en diferentes tipos de activos para reducir riesgos.",
    },
    answer: "D",
  },
  {
    id: 7,
    topic: "Educación Financiera",
    question: "¿Qué es la inflación?",
    options: {
      A: "La disminución de los precios de los productos.",
      B: "El aumento de salarios.",
      C: "Una caída del mercado de valores.",
      D: "El aumento general de los precios y la disminución del poder adquisitivo del dinero.",
    },
    answer: "D",
  },
  {
    id: 8,
    topic: "Educación Financiera",
    question: "¿Qué es una inversión?",
    options: {
      A: "Gastar dinero en cosas innecesarias.",
      B: "Pagar las facturas mensuales.",
      C: "Sacar dinero del banco.",
      D: "Destinar dinero hoy con la expectativa de obtener un beneficio futuro.",
    },
    answer: "D",
  },
  {
    id: 9,
    topic: "Educación Financiera",
    question: "¿Qué es la deuda buena y la deuda mala?",
    options: {
      A: "Toda deuda es mala.",
      B: "La buena es para lujos y la mala para necesidades.",
      C: "No existe diferencia, solo es deuda.",
      D: "La buena genera valor (ej. hipoteca) y la mala consume valor (ej. tarjetas de crédito con alto interés).",
    },
    answer: "D",
  },
  {
    id: 10,
    topic: "Educación Financiera",
    question: "¿Qué es el interés compuesto?",
    options: {
      A: "Pagar intereses solo una vez.",
      B: "Un tipo de préstamo.",
      C: "Un cobro por usar una tarjeta de crédito.",
      D: "Ganar intereses sobre tus intereses ya ganados.",
    },
    answer: "D",
  },
  {
    id: 11,
    topic: "Educación Financiera",
    question: "¿Qué es un fondo de emergencia?",
    options: {
      A: "Dinero para vacaciones.",
      B: "Un fondo de inversión de alto riesgo.",
      C: "Dinero para comprar una casa.",
      D: "Dinero ahorrado para gastos inesperados o crisis.",
    },
    answer: "D",
  },
  {
    id: 12,
    topic: "Educación Financiera",
    question: "¿Qué es la educación financiera?",
    options: {
      A: "Solo aprender a invertir en la bolsa.",
      B: "Pagar a un experto para que gestione tu dinero.",
      C: "Leer noticias económicas todos los días.",
      D: "El conocimiento y las habilidades para tomar decisiones financieras informadas.",
    },
    answer: "D",
  },
  {
    id: 13,
    topic: "Educación Financiera",
    question: "¿Qué son los gastos fijos?",
    options: {
      A: "Gastos que cambian mucho cada mes.",
      B: "Gastos para emergencias.",
      C: "Solo gastos de comida.",
      D: "Aquellos que se mantienen constantes cada mes, como el alquiler.",
    },
    answer: "D",
  },
  {
    id: 14,
    topic: "Educación Financiera",
    question: "¿Qué es el balance o estado de situación financiera?",
    options: {
      A: "Un registro de ingresos y gastos durante un período.",
      B: "La lista de clientes de una empresa.",
      C: "Un plan para el futuro financiero.",
      D: "Un resumen de los activos, pasivos y patrimonio en un momento dado.",
    },
    answer: "D",
  },
  {
    id: 15,
    topic: "Educación Financiera",
    question: "¿Qué es la libertad financiera?",
    options: {
      A: "No tener dinero ahorrado.",
      B: "Tener un trabajo bien pagado.",
      C: "Gastarse todo el dinero que se gana.",
      D: "Tener suficientes ingresos pasivos para cubrir tus gastos de vida.",
    },
    answer: "D",
  },
  {
    id: 16,
    topic: "Educación Financiera",
    question: "¿Qué es un activo intangible?",
    options: {
      A: "Una casa o un coche.",
      B: "Dinero en efectivo.",
      C: "Una deuda por pagar.",
      D: "Un activo que no tiene forma física, como una marca o patente.",
    },
    answer: "D",
  },
  {
    id: 17,
    topic: "Educación Financiera",
    question: '¿Qué es el "efecto bola de nieve" en el pago de deudas?',
    options: {
      A: "Pagar solo los intereses de las deudas.",
      B: "Pedir más préstamos para pagar los actuales.",
      C: "Ignorar las deudas hasta que desaparezcan.",
      D: "Pagar primero la deuda más pequeña para ganar impulso y luego seguir con las grandes.",
    },
    answer: "D",
  },
  {
    id: 18,
    topic: "Educación Financiera",
    question: "¿Qué es un fondo de inversión?",
    options: {
      A: "Una cuenta de ahorros para niños.",
      B: "Un tipo de tarjeta de crédito.",
      C: "Dinero en efectivo guardado en casa.",
      D: "Un portafolio de inversiones manejado por profesionales, donde varios inversores agrupan su dinero.",
    },
    answer: "D",
  },
  {
    id: 19,
    topic: "Educación Financiera",
    question: "¿Qué son los gastos variables?",
    options: {
      A: "Gastos que siempre son iguales.",
      B: "Solo gastos de transporte.",
      C: "Impuestos anuales.",
      D: "Aquellos que cambian mes a mes según el consumo o uso.",
    },
    answer: "D",
  },
  {
    id: 20,
    topic: "Educación Financiera",
    question: "¿Qué es el patrimonio neto?",
    options: {
      A: "Solo el dinero en tu cuenta bancaria.",
      B: "El total de tus deudas.",
      C: "Tus ingresos mensuales.",
      D: "El valor de tus activos menos tus pasivos (lo que posees menos lo que debes).",
    },
    answer: "D",
  },
  {
    id: 21,
    topic: "Educación Financiera",
    question: "¿Qué es la calificación crediticia o score de crédito?",
    options: {
      A: "Tu número de cuenta bancaria.",
      B: "Tu saldo de ahorros.",
      C: "Tu edad.",
      D: "Una evaluación de tu historial de pago de deudas y tu capacidad para pagar.",
    },
    answer: "D",
  },
  {
    id: 22,
    topic: "Educación Financiera",
    question: '¿Qué es el "robo de identidad" financiero?',
    options: {
      A: "Perder tu tarjeta de crédito.",
      B: "Olvidar la contraseña de tu banco online.",
      C: "Recibir publicidad no deseada por correo.",
      D: "Cuando alguien usa tu información personal para abrir cuentas o hacer compras fraudulentas.",
    },
    answer: "D",
  },
  {
    id: 23,
    topic: "Educación Financiera",
    question: "¿Cuál es la importancia de tener metas financieras?",
    options: {
      A: "Para gastar más dinero sin preocupación.",
      B: "Para impresionar a tus amigos.",
      C: "No son importantes si tus ingresos son altos.",
      D: "Proporcionan dirección y motivación para ahorrar e invertir eficazmente.",
    },
    answer: "D",
  },
  {
    id: 24,
    topic: "Educación Financiera",
    question: "¿Qué es un activo de bajo riesgo?",
    options: {
      A: "Una inversión en criptomonedas.",
      B: "Acciones de una startup tecnológica.",
      C: "Comprar billetes de lotería.",
      D: "Una inversión con poca probabilidad de perder dinero, como cuentas de ahorro o bonos del gobierno.",
    },
    answer: "D",
  },
  {
    id: 25,
    topic: "Educación Financiera",
    question: "¿Qué es la planificación para la jubilación?",
    options: {
      A: "Gastar todo tu dinero antes de la vejez.",
      B: "No pensar en el futuro financiero.",
      C: "Depender solo de la pensión del gobierno.",
      D: "Establecer un plan financiero para asegurar ingresos suficientes en la vejez.",
    },
    answer: "D",
  },
  {
    id: 26,
    topic: "Emprendimiento",
    question: "¿Qué es un emprendedor?",
    options: {
      A: "Un empleado de una gran empresa.",
      B: "Un inversor de bolsa.",
      C: "Un consumidor frecuente.",
      D: "Una persona que inicia un negocio asumiendo riesgos.",
    },
    answer: "D",
  },
  {
    id: 27,
    topic: "Emprendimiento",
    question: "¿Qué es un plan de negocios?",
    options: {
      A: "Una tarjeta de presentación.",
      B: "Un contrato con los empleados.",
      C: "Un registro de ventas diario.",
      D: "Un documento que describe los objetivos y estrategias de una empresa.",
    },
    answer: "D",
  },
  {
    id: 28,
    topic: "Emprendimiento",
    question: "¿Qué es la innovación en el emprendimiento?",
    options: {
      A: "Copiar un negocio exitoso.",
      B: "Vender productos a bajo precio.",
      C: "Hacer publicidad de un producto.",
      D: "La creación de algo nuevo o la mejora significativa de lo existente.",
    },
    answer: "D",
  },
  {
    id: 29,
    topic: "Emprendimiento",
    question: "¿Qué es un nicho de mercado?",
    options: {
      A: "Un mercado muy grande y general.",
      B: "Una tienda física.",
      C: "Un tipo de producto.",
      D: "Un segmento específico de consumidores con necesidades particulares.",
    },
    answer: "D",
  },
  {
    id: 30,
    topic: "Emprendimiento",
    question: "¿Qué es el valor agregado en un producto o servicio?",
    options: {
      A: "El precio de venta del producto.",
      B: "El costo de producción.",
      C: "La cantidad de productos vendidos.",
      D: "Una característica extra que lo hace más atractivo para el cliente.",
    },
    answer: "D",
  },
  {
    id: 31,
    topic: "Emprendimiento",
    question: "¿Qué es la propuesta de valor de un emprendimiento?",
    options: {
      A: "La ubicación física del negocio.",
      B: "El número de empleados.",
      C: "El nombre de la empresa.",
      D: "El beneficio único que ofrece a los clientes y lo distingue.",
    },
    answer: "D",
  },
  {
    id: 32,
    topic: "Emprendimiento",
    question: '¿Qué es el "brainstorming" en el proceso emprendedor?',
    options: {
      A: "Un estudio de mercado.",
      B: "La fase de venta del producto.",
      C: "La contabilidad del negocio.",
      D: "Una técnica para generar ideas creativas en grupo.",
    },
    answer: "D",
  },
  {
    id: 33,
    topic: "Emprendimiento",
    question: '¿Qué es un "pitch" de negocios?',
    options: {
      A: "Una discusión interna del equipo.",
      B: "Un informe financiero detallado.",
      C: "Un plan de marketing completo.",
      D: "Una presentación breve y persuasiva para vender una idea de negocio.",
    },
    answer: "D",
  },
  {
    id: 34,
    topic: "Emprendimiento",
    question:
      "¿Por qué es importante la investigación de mercado para un emprendedor?",
    options: {
      A: "Para copiar a la competencia.",
      B: "Solo para obtener financiación.",
      C: "No es importante si tienes una buena idea.",
      D: "Para entender a los clientes, la competencia y las tendencias.",
    },
    answer: "D",
  },
  {
    id: 35,
    topic: "Emprendimiento",
    question: "¿Qué es la segmentación de clientes?",
    options: {
      A: "Atraer a todos los clientes posibles.",
      B: "Vender solo un tipo de producto.",
      C: "El proceso de fabricación de un producto.",
      D: "Dividir el mercado en grupos de clientes con características similares.",
    },
    answer: "D",
  },
  {
    id: 36,
    topic: "Emprendimiento",
    question: "¿Cuál es el propósito de un modelo de negocio?",
    options: {
      A: "Ser un plan de marketing.",
      B: "Solo para obtener financiación bancaria.",
      C: "Un documento legal para registrar la empresa.",
      D: "Describir cómo una empresa crea, entrega y captura valor.",
    },
    answer: "D",
  },
  {
    id: 37,
    topic: "Emprendimiento",
    question: "¿Qué es la incubadora de empresas?",
    options: {
      A: "Una empresa muy grande y establecida.",
      B: "Un tipo de inversión bancaria.",
      C: "Una oficina compartida para cualquier tipo de negocio.",
      D: "Una organización que apoya a startups en sus primeras etapas.",
    },
    answer: "D",
  },
  {
    id: 38,
    topic: "Emprendimiento",
    question: "¿Qué es la resiliencia en el emprendimiento?",
    options: {
      A: "No tener problemas nunca.",
      B: "Ser muy rico.",
      C: "Solo trabajar duro.",
      D: "La capacidad de superar desafíos y adaptarse a los cambios.",
    },
    answer: "D",
  },
  {
    id: 39,
    topic: "Emprendimiento",
    question: "¿Qué es el networking en el mundo empresarial?",
    options: {
      A: "Solo vender productos.",
      B: "Usar internet para trabajar.",
      C: "Escribir códigos de programación.",
      D: "Establecer y mantener una red de contactos profesionales.",
    },
    answer: "D",
  },
  {
    id: 40,
    topic: "Emprendimiento",
    question: "¿Qué es un prototipo en el desarrollo de productos?",
    options: {
      A: "El producto final listo para la venta.",
      B: "Un dibujo en papel del producto.",
      C: "El embalaje del producto.",
      D: "Una versión inicial y simplificada de un producto para probarlo.",
    },
    answer: "D",
  },
  {
    id: 41,
    topic: "Emprendimiento",
    question: '¿Qué significa "pivotar" en un emprendimiento?',
    options: {
      A: "Cerrar el negocio.",
      B: "Mantener siempre la misma estrategia.",
      C: "Invertir más dinero en la idea original.",
      D: "Cambiar la dirección estratégica del negocio basándose en el aprendizaje.",
    },
    answer: "D",
  },
  {
    id: 42,
    topic: "Emprendimiento",
    question: "¿Qué es la ventaja competitiva de una empresa?",
    options: {
      A: "Tener el logo más bonito.",
      B: "Vender muchos productos baratos.",
      C: "No tener competidores.",
      D: "Aquello que la hace superior a sus competidores en el mercado.",
    },
    answer: "D",
  },
  {
    id: 43,
    topic: "Emprendimiento",
    question: "¿Qué es el lienzo de modelo de negocio (Business Model Canvas)?",
    options: {
      A: "Un programa de contabilidad.",
      B: "Un tipo de presentación de ventas.",
      C: "Un gráfico de ventas anuales.",
      D: "Una herramienta visual para diseñar y analizar modelos de negocio de forma estratégica.",
    },
    answer: "D",
  },
  {
    id: 44,
    topic: "Emprendimiento",
    question: "¿Qué es la viabilidad en un emprendimiento?",
    options: {
      A: "Tener mucho dinero para empezar.",
      B: "Ser famoso en redes sociales.",
      C: "Copiar a un competidor directo.",
      D: "La capacidad de un negocio para ser exitoso y sostenible a largo plazo.",
    },
    answer: "D",
  },
  {
    id: 45,
    topic: "Emprendimiento",
    question: '¿Qué es el "elevator pitch"?',
    options: {
      A: "Una charla muy larga sobre el negocio.",
      B: "Un documento legal para registrar la empresa.",
      C: "Una reunión con un inversor.",
      D: "Una presentación muy breve de tu idea de negocio, como si la hicieras en un ascensor.",
    },
    answer: "D",
  },
  {
    id: 46,
    topic: "Emprendimiento",
    question: "¿Cuál es la importancia de la pasión en el emprendimiento?",
    options: {
      A: "No es importante, solo se necesita dinero.",
      B: "Solo es importante al inicio del negocio.",
      C: "Solo sirve para convencer a inversores.",
      D: "Es el motor que impulsa al emprendedor a superar obstáculos y mantenerse motivado.",
    },
    answer: "D",
  },
  {
    id: 47,
    topic: "Emprendimiento",
    question:
      '¿Qué es el "lienzo de propuesta de valor" (Value Proposition Canvas)?',
    options: {
      A: "Un plan de marketing.",
      B: "Una hoja de cálculo para finanzas.",
      C: "Un listado de precios de productos.",
      D: "Una herramienta para asegurar que tu producto/servicio se alinee con las necesidades del cliente.",
    },
    answer: "D",
  },
  {
    id: 48,
    topic: "Emprendimiento",
    question: "¿Qué es la escalabilidad de un negocio?",
    options: {
      A: "Vender productos solo en una ciudad.",
      B: "Necesitar más empleados por cada nuevo cliente.",
      C: "No tener que invertir en el negocio.",
      D: "La capacidad de crecer y aumentar la producción o servicio sin aumentar proporcionalmente los costos.",
    },
    answer: "D",
  },
  {
    id: 49,
    topic: "Emprendimiento",
    question: '¿Qué es el "flujo de caja" en un negocio?',
    options: {
      A: "El número total de ventas realizadas.",
      B: "La cantidad de deuda que tiene la empresa.",
      C: "El valor total de los activos de la empresa.",
      D: "El movimiento de dinero que entra y sale de la empresa en un período determinado.",
    },
    answer: "D",
  },
  {
    id: 50,
    topic: "Emprendimiento",
    question: "¿Qué es el bootstrapping en el emprendimiento?",
    options: {
      A: "Obtener una gran inversión de un ángel inversor.",
      B: "Pedir muchos préstamos bancarios.",
      C: "Gastar todo el dinero rápidamente para crecer.",
      D: "Financiar un negocio utilizando solo ingresos propios o la reinversión de ganancias, sin inversión externa.",
    },
    answer: "D",
  },
];
