import type { Question } from "@/types";

export const questionsV1: Question[] = [
  {
    id: "1",
    topic: "Educación Financiera",
    question: "¿Qué es un presupuesto?",
    options: {
      A: "Un plan de gastos y ahorros.",
      B: "Una lista de deseos.",
      C: "Una cuenta bancaria.",
      D: "Un tipo de inversión.",
    },
    answer: "A",
  },
  {
    id: "2",
    topic: "Educación Financiera",
    question: "¿Por qué es importante ahorrar dinero?",
    options: {
      A: "Para pagar todas las deudas de una vez.",
      B: "Para tener seguridad financiera y alcanzar metas futuras.",
      C: "No es importante si tienes muchos ingresos.",
      D: "Solo para comprar artículos de lujo.",
    },
    answer: "B",
  },
  {
    id: "3",
    topic: "Educación Financiera",
    question: "¿Qué es el interés?",
    options: {
      A: "Un descuento en una compra.",
      B: "El costo de pedir dinero prestado o la ganancia por prestarlo.",
      C: "Un tipo de impuesto.",
      D: "El precio de un producto.",
    },
    answer: "B",
  },
  {
    id: "4",
    topic: "Educación Financiera",
    question: "¿Qué es el crédito?",
    options: {
      A: "Un regalo de dinero.",
      B: "La capacidad de pedir dinero prestado con la promesa de pagarlo después.",
      C: "Dinero en efectivo.",
      D: "Una cuenta de ahorros.",
    },
    answer: "B",
  },
  {
    id: "5",
    topic: "Educación Financiera",
    question: "¿Cuál es la diferencia entre un activo y un pasivo?",
    options: {
      A: "Un activo es una cuenta de ahorros y un pasivo es una inversión.",
      B: "Un activo te genera dinero y un pasivo te quita dinero.",
      C: "No hay diferencia, son lo mismo.",
      D: "Un activo es algo viejo y un pasivo es algo nuevo.",
    },
    answer: "B",
  },
  {
    id: "6",
    topic: "Educación Financiera",
    question: "¿Qué es la diversificación de inversiones?",
    options: {
      A: "Distribuir las inversiones en diferentes tipos de activos para reducir riesgos.",
      B: "Poner todo el dinero en una sola inversión.",
      C: "Solo invertir en acciones.",
      D: "Invertir en un solo país.",
    },
    answer: "A",
  },
  {
    id: "7",
    topic: "Educación Financiera",
    question: "¿Qué es la inflación?",
    options: {
      A: "El aumento general de los precios y la disminución del poder adquisitivo del dinero.",
      B: "El aumento de salarios.",
      C: "Una caída del mercado de valores.",
      D: "La disminución de los precios de los productos.",
    },
    answer: "A",
  },
  {
    id: "8",
    topic: "Educación Financiera",
    question: "¿Qué es una inversión?",
    options: {
      A: "Pagar las facturas mensuales.",
      B: "Sacar dinero del banco.",
      C: "Destinar dinero hoy con la expectativa de obtener un beneficio futuro.",
      D: "Gastar dinero en cosas innecesarias.",
    },
    answer: "C",
  },
  {
    id: "9",
    topic: "Educación Financiera",
    question: "¿Qué es la deuda buena y la deuda mala?",
    options: {
      A: "La buena genera valor (ej. hipoteca) y la mala consume valor (ej. tarjetas de crédito con alto interés).",
      B: "Toda deuda es mala.",
      C: "No existe diferencia, solo es deuda.",
      D: "La buena es para lujos y la mala para necesidades.",
    },
    answer: "A",
  },
  {
    id: "10",
    topic: "Educación Financiera",
    question: "¿Qué es el interés compuesto?",
    options: {
      A: "Un tipo de préstamo.",
      B: "Pagar intereses solo una vez.",
      C: "Ganar intereses sobre tus intereses ya ganados.",
      D: "Un cobro por usar una tarjeta de crédito.",
    },
    answer: "C",
  },
  {
    id: "11",
    topic: "Educación Financiera",
    question: "¿Qué es un fondo de emergencia?",
    options: {
      A: "Dinero para vacaciones.",
      B: "Dinero para comprar una casa.",
      C: "Dinero ahorrado para gastos inesperados o crisis.",
      D: "Un fondo de inversión de alto riesgo.",
    },
    answer: "C",
  },
  {
    id: "12",
    topic: "Educación Financiera",
    question: "¿Qué es la educación financiera?",
    options: {
      A: "El conocimiento y las habilidades para tomar decisiones financieras informadas.",
      B: "Pagar a un experto para que gestione tu dinero.",
      C: "Leer noticias económicas todos los días.",
      D: "Solo aprender a invertir en la bolsa.",
    },
    answer: "A",
  },
  {
    id: "13",
    topic: "Educación Financiera",
    question: "¿Qué son los gastos fijos?",
    options: {
      A: "Gastos que cambian mucho cada mes.",
      B: "Aquellos que se mantienen constantes cada mes, como el alquiler.",
      C: "Solo gastos de comida.",
      D: "Gastos para emergencias.",
    },
    answer: "B",
  },
  {
    id: "14",
    topic: "Educación Financiera",
    question: "¿Qué es el balance o estado de situación financiera?",
    options: {
      A: "Un plan para el futuro financiero.",
      B: "Un resumen de los activos, pasivos y patrimonio en un momento dado.",
      C: "Un registro de ingresos y gastos durante un período.",
      D: "La lista de clientes de una empresa.",
    },
    answer: "B",
  },
  {
    id: "15",
    topic: "Educación Financiera",
    question: "¿Qué es la libertad financiera?",
    options: {
      A: "Tener suficientes ingresos pasivos para cubrir tus gastos de vida.",
      B: "No tener dinero ahorrado.",
      C: "Gastarse todo el dinero que se gana.",
      D: "Tener un trabajo bien pagado.",
    },
    answer: "A",
  },
  {
    id: "16",
    topic: "Educación Financiera",
    question: "¿Qué es un activo intangible?",
    options: {
      A: "Dinero en efectivo.",
      B: "Un activo que no tiene forma física, como una marca o patente.",
      C: "Una deuda por pagar.",
      D: "Una casa o un coche.",
    },
    answer: "B",
  },
  {
    id: "17",
    topic: "Educación Financiera",
    question: '¿Qué es el "efecto bola de nieve" en el pago de deudas?',
    options: {
      A: "Ignorar las deudas hasta que desaparezcan.",
      B: "Pedir más préstamos para pagar los actuales.",
      C: "Pagar primero la deuda más pequeña para ganar impulso y luego seguir con las grandes.",
      D: "Pagar solo los intereses de las deudas.",
    },
    answer: "C",
  },
  {
    id: "18",
    topic: "Educación Financiera",
    question: "¿Qué es un fondo de inversión?",
    options: {
      A: "Un tipo de tarjeta de crédito.",
      B: "Un portafolio de inversiones manejado por profesionales, donde varios inversores agrupan su dinero.",
      C: "Una cuenta de ahorros para niños.",
      D: "Dinero en efectivo guardado en casa.",
    },
    answer: "B",
  },
  {
    id: "19",
    topic: "Educación Financiera",
    question: "¿Qué son los gastos variables?",
    options: {
      A: "Aquellos que cambian mes a mes según el consumo o uso.",
      B: "Impuestos anuales.",
      C: "Solo gastos de transporte.",
      D: "Gastos que siempre son iguales.",
    },
    answer: "A",
  },
  {
    id: "20",
    topic: "Educación Financiera",
    question: "¿Qué es el patrimonio neto?",
    options: {
      A: "Tus ingresos mensuales.",
      B: "El total de tus deudas.",
      C: "Solo el dinero en tu cuenta bancaria.",
      D: "El valor de tus activos menos tus pasivos (lo que posees menos lo que debes).",
    },
    answer: "D",
  },
  {
    id: "21",
    topic: "Educación Financiera",
    question: "¿Qué es la calificación crediticia o score de crédito?",
    options: {
      A: "Tu edad.",
      B: "Tu saldo de ahorros.",
      C: "Una evaluación de tu historial de pago de deudas y tu capacidad para pagar.",
      D: "Tu número de cuenta bancaria.",
    },
    answer: "C",
  },
  {
    id: "22",
    topic: "Educación Financiera",
    question: '¿Qué es el "robo de identidad" financiero?',
    options: {
      A: "Cuando alguien usa tu información personal para abrir cuentas o hacer compras fraudulentas.",
      B: "Olvidar la contraseña de tu banco online.",
      C: "Perder tu tarjeta de crédito.",
      D: "Recibir publicidad no deseada por correo.",
    },
    answer: "A",
  },
  {
    id: "23",
    topic: "Educación Financiera",
    question: "¿Cuál es la importancia de tener metas financieras?",
    options: {
      A: "Para impresionar a tus amigos.",
      B: "Proporcionan dirección y motivación para ahorrar e invertir eficazmente.",
      C: "No son importantes si tus ingresos son altos.",
      D: "Para gastar más dinero sin preocupación.",
    },
    answer: "B",
  },
  {
    id: "24",
    topic: "Educación Financiera",
    question: "¿Qué es un activo de bajo riesgo?",
    options: {
      A: "Una inversión con poca probabilidad de perder dinero, como cuentas de ahorro o bonos del gobierno.",
      B: "Una inversión en criptomonedas.",
      C: "Acciones de una startup tecnológica.",
      D: "Comprar billetes de lotería.",
    },
    answer: "A",
  },
  {
    id: "25",
    topic: "Educación Financiera",
    question: "¿Qué es la planificación para la jubilación?",
    options: {
      A: "No pensar en el futuro financiero.",
      B: "Establecer un plan financiero para asegurar ingresos suficientes en la vejez.",
      C: "Gastar todo tu dinero antes de la vejez.",
      D: "Depender solo de la pensión del gobierno.",
    },
    answer: "B",
  },
  {
    id: "26",
    topic: "Emprendimiento",
    question: "¿Qué es un emprendedor?",
    options: {
      A: "Un empleado de una gran empresa.",
      B: "Una persona que inicia un negocio asumiendo riesgos.",
      C: "Un consumidor frecuente.",
      D: "Un inversor de bolsa.",
    },
    answer: "B",
  },
  {
    id: "27",
    topic: "Emprendimiento",
    question: "¿Qué es un plan de negocios?",
    options: {
      A: "Un documento que describe los objetivos y estrategias de una empresa.",
      B: "Un registro de ventas diario.",
      C: "Una tarjeta de presentación.",
      D: "Un contrato con los empleados.",
    },
    answer: "A",
  },
  {
    id: "28",
    topic: "Emprendimiento",
    question: "¿Qué es la innovación en el emprendimiento?",
    options: {
      A: "Copiar un negocio exitoso.",
      B: "Hacer publicidad de un producto.",
      C: "La creación de algo nuevo o la mejora significativa de lo existente.",
      D: "Vender productos a bajo precio.",
    },
    answer: "C",
  },
  {
    id: "29",
    topic: "Emprendimiento",
    question: "¿Qué es un nicho de mercado?",
    options: {
      A: "Un segmento específico de consumidores con necesidades particulares.",
      B: "Un mercado muy grande y general.",
      C: "Una tienda física.",
      D: "Un tipo de producto.",
    },
    answer: "A",
  },
  {
    id: "30",
    topic: "Emprendimiento",
    question: "¿Qué es el valor agregado en un producto o servicio?",
    options: {
      A: "El costo de producción.",
      B: "Una característica extra que lo hace más atractivo para el cliente.",
      C: "El precio de venta del producto.",
      D: "La cantidad de productos vendidos.",
    },
    answer: "B",
  },
  {
    id: "31",
    topic: "Emprendimiento",
    question: "¿Qué es la propuesta de valor de un emprendimiento?",
    options: {
      A: "El beneficio único que ofrece a los clientes y lo distingue.",
      B: "El nombre de la empresa.",
      C: "La ubicación física del negocio.",
      D: "El número de empleados.",
    },
    answer: "A",
  },
  {
    id: "32",
    topic: "Emprendimiento",
    question: '¿Qué es el "brainstorming" en el proceso emprendedor?',
    options: {
      A: "La contabilidad del negocio.",
      B: "Un estudio de mercado.",
      C: "La fase de venta del producto.",
      D: "Una técnica para generar ideas creativas en grupo.",
    },
    answer: "D",
  },
  {
    id: "33",
    topic: "Emprendimiento",
    question: '¿Qué es un "pitch" de negocios?',
    options: {
      A: "Un informe financiero detallado.",
      B: "Una presentación breve y persuasiva para vender una idea de negocio.",
      C: "Una discusión interna del equipo.",
      D: "Un plan de marketing completo.",
    },
    answer: "B",
  },
  {
    id: "34",
    topic: "Emprendimiento",
    question:
      "¿Por qué es importante la investigación de mercado para un emprendedor?",
    options: {
      A: "Para entender a los clientes, la competencia y las tendencias.",
      B: "No es importante si tienes una buena idea.",
      C: "Para copiar a la competencia.",
      D: "Solo para obtener financiación.",
    },
    answer: "A",
  },
  {
    id: "35",
    topic: "Emprendimiento",
    question: "¿Qué es la segmentación de clientes?",
    options: {
      A: "Dividir el mercado en grupos de clientes con características similares.",
      B: "El proceso de fabricación de un producto.",
      C: "Vender solo un tipo de producto.",
      D: "Atraer a todos los clientes posibles.",
    },
    answer: "A",
  },
  {
    id: "36",
    topic: "Emprendimiento",
    question: "¿Cuál es el propósito de un modelo de negocio?",
    options: {
      A: "Un documento legal para registrar la empresa.",
      B: "Describir cómo una empresa crea, entrega y captura valor.",
      C: "Ser un plan de marketing.",
      D: "Solo para obtener financiación bancaria.",
    },
    answer: "B",
  },
  {
    id: "37",
    topic: "Emprendimiento",
    question: "¿Qué es la incubadora de empresas?",
    options: {
      A: "Un tipo de inversión bancaria.",
      B: "Una organización que apoya a startups en sus primeras etapas.",
      C: "Una empresa muy grande y establecida.",
      D: "Una oficina compartida para cualquier tipo de negocio.",
    },
    answer: "B",
  },
  {
    id: "38",
    topic: "Emprendimiento",
    question: "¿Qué es la resiliencia en el emprendimiento?",
    options: {
      A: "Solo trabajar duro.",
      B: "No tener problemas nunca.",
      C: "La capacidad de superar desafíos y adaptarse a los cambios.",
      D: "Ser muy rico.",
    },
    answer: "C",
  },
  {
    id: "39",
    topic: "Emprendimiento",
    question: "¿Qué es el networking en el mundo empresarial?",
    options: {
      A: "Establecer y mantener una red de contactos profesionales.",
      B: "Usar internet para trabajar.",
      C: "Solo vender productos.",
      D: "Escribir códigos de programación.",
    },
    answer: "A",
  },
  {
    id: "40",
    topic: "Emprendimiento",
    question: "¿Qué es un prototipo en el desarrollo de productos?",
    options: {
      A: "Un dibujo en papel del producto.",
      B: "El producto final listo para la venta.",
      C: "Una versión inicial y simplificada de un producto para probarlo.",
      D: "El embalaje del producto.",
    },
    answer: "C",
  },
  {
    id: "41",
    topic: "Emprendimiento",
    question: '¿Qué significa "pivotar" en un emprendimiento?',
    options: {
      A: "Cerrar el negocio.",
      B: "Cambiar la dirección estratégica del negocio basándose en el aprendizaje.",
      C: "Invertir más dinero en la idea original.",
      D: "Mantener siempre la misma estrategia.",
    },
    answer: "B",
  },
  {
    id: "42",
    topic: "Emprendimiento",
    question: "¿Qué es la ventaja competitiva de una empresa?",
    options: {
      A: "Aquello que la hace superior a sus competidores en el mercado.",
      B: "Vender muchos productos baratos.",
      C: "Tener el logo más bonito.",
      D: "No tener competidores.",
    },
    answer: "A",
  },
  {
    id: "43",
    topic: "Emprendimiento",
    question: "¿Qué es el lienzo de modelo de negocio (Business Model Canvas)?",
    options: {
      A: "Un programa de contabilidad.",
      B: "Un tipo de presentación de ventas.",
      C: "Una herramienta visual para diseñar y analizar modelos de negocio de forma estratégica.",
      D: "Un gráfico de ventas anuales.",
    },
    answer: "C",
  },
  {
    id: "44",
    topic: "Emprendimiento",
    question: "¿Qué es la viabilidad en un emprendimiento?",
    options: {
      A: "La capacidad de un negocio para ser exitoso y sostenible a largo plazo.",
      B: "Ser famoso en redes sociales.",
      C: "Copiar a un competidor directo.",
      D: "Tener mucho dinero para empezar.",
    },
    answer: "A",
  },
  {
    id: "45",
    topic: "Emprendimiento",
    question: '¿Qué es el "elevator pitch"?',
    options: {
      A: "Una presentación muy breve de tu idea de negocio, como si la hicieras en un ascensor.",
      B: "Una reunión con un inversor.",
      C: "Una charla muy larga sobre el negocio.",
      D: "Un documento legal para registrar la empresa.",
    },
    answer: "A",
  },
  {
    id: "46",
    topic: "Emprendimiento",
    question: "¿Cuál es la importancia de la pasión en el emprendimiento?",
    options: {
      A: "Solo es importante al inicio del negocio.",
      B: "Es el motor que impulsa al emprendedor a superar obstáculos y mantenerse motivado.",
      C: "No es importante, solo se necesita dinero.",
      D: "Solo sirve para convencer a inversores.",
    },
    answer: "B",
  },
  {
    id: "47",
    topic: "Emprendimiento",
    question:
      '¿Qué es el "lienzo de propuesta de valor" (Value Proposition Canvas)?',
    options: {
      A: "Una herramienta para asegurar que tu producto/servicio se alinee con las necesidades del cliente.",
      B: "Un listado de precios de productos.",
      C: "Un plan de marketing.",
      D: "Una hoja de cálculo para finanzas.",
    },
    answer: "A",
  },
  {
    id: "48",
    topic: "Emprendimiento",
    question: "¿Qué es la escalabilidad de un negocio?",
    options: {
      A: "Necesitar más empleados por cada nuevo cliente.",
      B: "La capacidad de crecer y aumentar la producción o servicio sin aumentar proporcionalmente los costos.",
      C: "Vender productos solo en una ciudad.",
      D: "No tener que invertir en el negocio.",
    },
    answer: "B",
  },
  {
    id: "49",
    topic: "Emprendimiento",
    question: '¿Qué es el "flujo de caja" en un negocio?',
    options: {
      A: "La cantidad de deuda que tiene la empresa.",
      B: "El movimiento de dinero que entra y sale de la empresa en un período determinado.",
      C: "El número total de ventas realizadas.",
      D: "El valor total de los activos de la empresa.",
    },
    answer: "B",
  },
  {
    id: "50",
    topic: "Emprendimiento",
    question: "¿Qué es el bootstrapping en el emprendimiento?",
    options: {
      A: "Financiar un negocio utilizando solo ingresos propios o la reinversión de ganancias, sin inversión externa.",
      B: "Pedir muchos préstamos bancarios.",
      C: "Obtener una gran inversión de un ángel inversor.",
      D: "Gastar todo el dinero rápidamente para crecer.",
    },
    answer: "A",
  },
];
